const url = {
  genNumStr: '/auth/common/genNumStr',
  genShortNumStr: '/auth/common/genShortNumStr',
  medicalTypeList: '/reservation/medicalType/list', // 医技类型列表
  loadMedicalTypeList: '/reservation/medicalType/loadMedicalTypeList',
  getMedicalTypeList: '/reservation/medicalType/getMedicalTypeList/',
  officeList: '/auth/office/getHasPerssionDeprtment', // 科室列表
  getOfficeTree: '/auth/office/getOfficeTree/',
  medicalTypeSave: '/reservation/medicalType/save',
  medicalTypeUpdateStatus: '/reservation/medicalType/updateStatus',
  medicalTypeDelete: '/reservation/medicalType/delete',
  medicalProjectList: '/reservation/medicalProject/list',
  medicalProjectSave: '/reservation/medicalProject/save',
  medicalProjectUpdateStatus: '/reservation/medicalProject/updateStatus',
  medicalProjectDelete: '/reservation/medicalProject/delete',
  loadDeviceList: '/reservation/device/loadDeviceList',
  deviceList: '/reservation/device/list',
  deviceSave: '/reservation/device/save',
  deviceUpdateStatus: '/reservation/device/updateStatus',
  deviceDelete: '/reservation/device/delete',
  loadQueueList: '/reservation/queue/loadQueueList',
  queueList: '/reservation/queue/list',
  queueSave: '/reservation/queue/save',
  queueDelete: '/reservation/queue/delete',
  workPeopleList: '/auth/workPeople/list',
  workPeopleSave: '/auth/workPeople/save',
  workPeopleDelete: '/auth/workPeople/delete',
  officeTimeList: '/reservation/officeTime/list',
  officeTimeSave: '/reservation/officeTime/save',
  officeTimeDelete: '/reservation/officeTime/delete',
  blackList: '/reservation/blacklist/find',
  blackListSave: '/reservation/blacklist/save',
  blackListDelete: '/reservation/blacklist/delete',
  adfindAll: '/api/txBannerPosition/findAll',
  adList: '/api/txBannerPosition/list',
  adSave: '/api/txBannerPosition/save',
  adDelete: '/api/txBannerPosition/delete',
  mainBannerList: '/api/txMainBanner/list',
  mainBannerSave: '/api/txMainBanner/save',
  mainBannerDelete: '/api/txMainBanner/delete',
  uploadFile: `/reservation/common/uploadFile`,
  getDict: `/auth/dict/getChildrenByCode`,
  loadCategoryById: '/api/category/findById',
  categoryList: '/api/category/list',
  categorySave: '/api/category/save',
  categoryDelete: '/api/category/delete',
  articleList: '/api/article/list',
  articleSave: '/api/article/save',
  articleDelete: '/api/article/delete',
  wxMenuList: '/api/wxMenu/list',
  wxMenuSave: '/api/wxMenu/save',
  wxMenuDelete: '/api/wxMenu/delete',
  loadWxMenuTypeList: '/api/wxMenuType/findAll',
  wxMenuTypeList: '/api/wxMenuType/list',
  wxMenuTypeSave: '/api/wxMenuType/save',
  wxMenuTypeDelete: '/api/wxMenuType/delete',
  scheduleList: '/reservation/schedule/listPage',
  scheduleAllList: '/reservation/schedule/getAllSchedule',
  scheduleSave: '/reservation/schedule/saveSchedule',
  scheduleDelete: '/reservation/schedule/delete',
  scheduleDetailListByScheduleId: '/reservation/scheduleDetail/findByScheduleId',
  scheduleDetailList: '/reservation/scheduleDetail/listPage',
  scheduleDetailSave: '/reservation/scheduleDetail/saveSchedule',
  scheduleDetailDelete: '/reservation/scheduleDetail/delete',
  sourcePlanList: '/reservation/sourcePlan/listPage',
  sourcePlanSave: '/reservation/sourcePlan/saveSourcePlan',
  sourcePlanBatchSave: '/reservation/sourcePlan/batchSaveSourcePlan',
  sourcePlanDelete: '/reservation/sourcePlan/delete',
  sourcePlanDetailList: '/reservation/sourcePlanDetail/listPage',
  sourcePlanDetailSave: '/reservation/sourcePlanDetail/saveSchedule',
  sourcePlanDetailDelete: '/reservation/sourcePlanDetail/delete',
  sourcePoolListByDept: '/reservation/sourcePool/getSourcePoolList',
  holidayAllList: '/reservation/holidayConfigure/findAll',
  holidayList: '/reservation/holidayConfigure/listPage',
  holidaySave: '/reservation/holidayConfigure/save',
  holidayDelete: '/reservation/holidayConfigure/delete',
  holidayInit: '/reservation/holidayConfigure/initHolidayConfigure',
  sourcePoolListByDeptAndDate: '/reservation/sourcePool/querySourcePoolList',
  modifySourcePlan: '/reservation/sourcePlan/updateSourcePlan'
}

export default {
  ...url
}
